Pin PIP version for pip-compile job
This commit pins `pip==22.0.0` in the `tox` environment `pip-compile` as
later versions of it are not properly working, causing the following
failure when running the scheduled CI via GH Actions:

```
AttributeError: 'function' object has no attribute 'cache_clear'
```

Signed-off-by: Jonathan Gangi <jgangi@redhat.com>